server:
  port: 1234
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studentdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: boss
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
   
