# Development configurations

server:
  port: 1010

  
spring:
  datasource:
    url: jdbc:h2::mem:devdb
    driver-class-name: org.h2.Driver
    username: root
    password: boss
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
