server:
  port: 1234

  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: boss
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
   
# To disable the swagger-ui
#springdoc:
#  swagger-ui:
#    enabled: false
   