server:
  port: 1234

  
spring:
  datasource:
     url: jdbc:h2:mem:testdb
     driverClassName: org.h2.Driver
     username: boss
     password: boss
#    url: jdbc:postgresql://localhost:5432/bookdb
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: boss
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    open-in-view: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
   
# To disable the swagger-ui
#springdoc:
#  swagger-ui:
#    enabled: false
   