server:
  port: 5050

#To disable the banner
spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:mariadb://localhost:1996/jasondb?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: boss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
       
# Spring security configurations.,
  security:
    user:
      name: boss
      password: boss
      
# Java Mail Service Configurations.,
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${Email}
    password: ${Password}
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
#spring.mail.properties.mail.smtp.starttls.enable : true
#spring.mail.properties.mail.smtp.starttls.required : true
#spring.mail.properties.mail.smtp.auth : true

#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
  
