server:
  port: 5050

#To disable the banner
spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:mariadb://localhost:1996/jasondb?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: boss
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
       
# Spring security configurations.,
  security:
    user:
      name: boss
      password: boss
      
# Java Mail Service Configurations.,
  mail:
    host: smtp.gmail.com
    port: 587
    username: naveenkrishnawodeyar@gmail.com
    password: tzjccfyolwkcznbd
    protocol: TLSv1.2
    test-connection: true
    

  
